domain_path: /home/wenting/Sitina1/firmware/ap/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
